version: "3.7"

services:
  database:
    container_name: database
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: P12345p
      MYSQL_DATABASE: bookstore_db
      MYSQL_USER: clarusway
      MYSQL_PASSWORD: Clarusway_1
    networks:
      - clarusnet
  
  myapp:
    container_name: myapp
    image: nalladocker/dockerization-webapi:latest 
    restart: always
    depends_on:
      - database
    ports:
      - 80:80
    networks:
      - clarusnet

networks:
  clarusnet:
